name=durjoyFirebase
version=1.0.0
author=Rakibul Hassan
maintainer=DurjoyRakibul <durjoy28mail@email.com>
sentence=Lightweight Firebase REST client for ESP8266
paragraph=Minimal Firebase Realtime Database REST client using HTTPS without official Firebase library.
category=Communication
url=https://github.com/DurjoyRakibul/durjoyFirebase
architectures=esp8266
